version: "3.8"

volumes:
  oc-www:
    external: true
  db_data:

services:
  oc-apache-php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: oc-apache-php
    ports:
      - "83:80"          # Host-Port jetzt 83
    volumes:
      - oc-www:/var/www/html
    restart: always

  oc-mariadb:
    image: mariadb:latest
    container_name: oc-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: DeineRootPasswort
      MYSQL_DATABASE: DeineDatenbank
      MYSQL_USER: DeinUser
      MYSQL_PASSWORD: DeinDatenbankPasswort
    volumes:
      - db_data:/var/lib/mysql
    restart: always

  oc-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: oc-phpmyadmin
    environment:
      PMA_HOST: oc-mariadb
      PMA_PORT: 3306
    ports:
      - "8081:80"
    depends_on:
      - oc-mariadb
    restart: always

  oc-sftp:
    image: atmoz/sftp
    container_name: oc-sftp
    ports:
      - "2223:22"
    volumes:
      - oc-www:/home/oc_user/web
    environment:
      SFTP_USERS: "oc_user:Anfdre212Anfdre212:1001:33:web"
    restart: always
